### ISSUE TITLE
Could The api note  python version,and add requirements.txt?

### ISSUE THREAD

**Issue by DavideHe** [jspenmar/monodepth_benchmark#3]
In api/data/export_kitti_depth_benchmark.py 
some syntax do not support in python3.6
and numpy should update 1.21.x ,but python3.6 not support this 

mybe there are other error by lib version or pytho version,so if  ok , add information of python version and requirements.txt.

**Comment by jspenmar** [comment]
I have now added this information to the README. Please note that exact versions of each library (including Python) are already shown in [environment.yml](https://github.com/jspenmar/monodepth_benchmark/blob/main/docker/environment.yml).
