### ISSUE TITLE
Highest precision configuration

### ISSUE THREAD

**Issue by kebijuelun** [jspenmar/monodepth_benchmark#5]
Hi, thanks for the wonderful codebase.

I would like to ask which configuration has the highest accuracy on KITTI Eigen and SYNS-Patches respectively? The corresponding precision of these experimental configurations is not found in readme.

Look forward for your reply, thanks.

**Comment by jspenmar** [comment]
Hi,

Thanks for the interest!

One of the top performers across both datasets was HRDepth, which also uses the Monodepth2 losses. However, for the full results I would recommend checking the [full paper](https://arxiv.org/pdf/2208.01489.pdf)

Kind regards,
Jaime
________________________________
From: stefan_liu ***@***.***>
Sent: Saturday, February 4, 2023 3:14 PM
To: jspenmar/monodepth_benchmark ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jspenmar/monodepth_benchmark] Highest precision configuration (Issue #5)


Hi, thanks for the wonderful codebase.

I would like to ask which configuration has the highest accuracy on KITTI Eigen and SYNS-Patches respectively? The corresponding precision of these experimental configurations is not found in readme.

Look forward for your reply, thanks.
