### ISSUE TITLE
Camera parameters of SYNS-Patches dataset

### ISSUE THREAD

**Issue by kamzero** [jspenmar/monodepth_benchmark#6]
Hello,

I am working on a project that involves monocular depth estimation using SYNS-Patches dataset. I would like to request the camera parameters of this dataset, especially intrinsics such as focal length and principal point. 

Could you please provide me with these information or point me to where I can find them? I appreciate your help.

Thank you.

**Comment by jspenmar** [comment]
Hi,

You can find the function that returns the intrinsic parameters here (https://github.com/jspenmar/monodepth_benchmark/blob/295a6ee2dfee18d1a863768e75a28c6f705594e1/src/devkits/syns_patches.py#L115).
You can also use the dataset class (https://github.com/jspenmar/monodepth_benchmark/blob/295a6ee2dfee18d1a863768e75a28c6f705594e1/src/datasets/syns_patches.py#L19) to load the images and intrinsics.

Kind regards,
Jaime

________________________________
From: JXR ***@***.***>
Sent: Friday, February 17, 2023 5:07 AM
To: jspenmar/monodepth_benchmark ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jspenmar/monodepth_benchmark] Camera parameters of SYNS-Patches dataset (Issue #6)


Hello,

I am working on a project that involves monocular depth estimation using SYNS-Patches dataset. I would like to request the camera parameters of this dataset, especially intrinsics such as focal length and principal point.

Could you please provide me with these information or point me to where I can find them? I appreciate your help.

Thank you.
