### ISSUE TITLE
What is the basis of the 0.01 scaling factor in pose.py?

### ISSUE THREAD

**Issue by YDayoub** [jspenmar/monodepth_benchmark#7]

**Comment by jspenmar** [comment]
Hi, 

We follow the reference implementations of SfM-Learner & Monodepth2. This scaling factor is added for additional stability during training. Please see https://github.com/nianticlabs/monodepth2/issues/260

Thanks,
Jaime

**Comment by YDayoub** [comment]
Thank you for the reply.
